<a href="https://colab.research.google.com/github/YuanChenhang/USAAIO/blob/main/PyTorch_Tensors%2C_creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import necessary libraries**

In [ ]:
import torch
import numpy as np

# **Major differences between PyTorch tensors and NumPy arrays**

1. A tensor has attribute `requires_grad` that it may be `True` (enables autograd) or `False` (disables autograd).

   But an array does not have this (you may intuitively understand that an array always has `requires_grad` to be `False`).

2. A tensor has attribute `device` that it may be put on GPU (`cuda`) or `cpu`.

   But an array does not have this (you may intuitively understand that an array always has `device` to be `cpu`).

**Tensor default attribute values**

1. `requires_grad` is `False`.

2. `device` is `cpu`.

# **Create tensors from lists/tuples**

**Create 0-dim tensors**

In [ ]:
x = 4.1
y = torch.tensor(x)
print(f"y is {y}")
print(f"The dimension of y is {y.ndim}")
print(f"The shape of y is {y.shape}")
print(f"The data type of y is {y.dtype}")
print(f"The requires_grad of y is {y.requires_grad}")
print(f"The device of y is {y.device}")

y is 4.099999904632568
The dimension of y is 0
The shape of y is torch.Size([])
The data type of y is torch.float32
The requires_grad of y is False
The device of y is cpu


**Create 1-dim tensors**

In [ ]:
x = [4.1] # Also try x = [1, 2.3, -.5]
y = torch.tensor(x, requires_grad = True)
print(f"y is {y}")
print(f"The dimension of y is {y.ndim}")
print(f"The shape of y is {y.shape}")
print(f"The data type of y is {y.dtype}")
print(f"The requires_grad of y is {y.requires_grad}")
print(f"The device of y is {y.device}")

y is tensor([4.1000], requires_grad=True)
The dimension of y is 1
The shape of y is torch.Size([1])
The data type of y is torch.float32
The requires_grad of y is True
The device of y is cpu


**Create 2-dim tensors**

In [ ]:
x = [[4.1]] # Also try x = [[1, 2.3, -.5]], [[1], [2.3], [-.5]], [[1, 2], [3, 4], [5, 6]]
y = torch.tensor(x, device = 'cuda')
print(f"y is {y}")
print(f"The dimension of y is {y.ndim}")
print(f"The shape of y is {y.shape}")
print(f"The data type of y is {y.dtype}")
print(f"The requires_grad of y is {y.requires_grad}")
print(f"The device of y is {y.device}")

y is tensor([[4.1000]], device='cuda:0')
The dimension of y is 2
The shape of y is torch.Size([1, 1])
The data type of y is torch.float32
The requires_grad of y is False
The device of y is cuda:0


**Create 3-dim tensors**

In [ ]:
x = [[[4.1]]] # Also try x = [[[1, 2.3, -.5]]], [[[1], [2.3], [-.5]]], [[[1]], [[2.3]], [[-.5]]], [[[1, 2], [3, 4], [5, 6]], [[10, 20], [30, 40], [50, 60]]]
y = torch.tensor(x, requires_grad = True, device = 'cuda')
print(f"y is {y}")
print(f"The dimension of y is {y.ndim}")
print(f"The shape of y is {y.shape}")
print(f"The data type of y is {y.dtype}")
print(f"The requires_grad of y is {y.requires_grad}")
print(f"The device of y is {y.device}")

y is tensor([[[4.1000]]], device='cuda:0', requires_grad=True)
The dimension of y is 3
The shape of y is torch.Size([1, 1, 1])
The data type of y is torch.float32
The requires_grad of y is True
The device of y is cuda:0


# **Create 1-dim tensors from**

* `torch.arange`

* `torch.linspace`

In [ ]:
x = torch.arange(3, 8, 2)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is tensor([3, 5, 7])
The dimension of x is 1
The shape of x is torch.Size([3])
The data type of x is torch.int64
The requires_grad of x is False
The device of x is cpu


In [ ]:
x = torch.linspace(10,20,11)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is tensor([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])
The dimension of x is 1
The shape of x is torch.Size([11])
The data type of x is torch.float32
The requires_grad of x is False
The device of x is cpu


# **Create tensors from numpy arrays**

**Create 0-dim tensors**

In [ ]:
x = np.array(-2.5)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")

y = torch.tensor(x)
print(f"y is {y}")
print(f"The dimension of y is {y.ndim}")
print(f"The shape of y is {y.shape}")
print(f"The data type of y is {y.dtype}")
print(f"The requires_grad of y is {y.requires_grad}")
print(f"The device of y is {y.device}")

x is -2.5
The dimension of x is 0
The shape of x is ()
The data type of x is float64
y is -2.5
The dimension of y is 0
The shape of y is torch.Size([])
The data type of y is torch.float64
The requires_grad of y is False
The device of y is cpu


**Create 1-dim tensors**

In [ ]:
x = np.array([4.1]) # Also try x = np.array([1, 2.3, -.5])
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")

y = torch.tensor(x, requires_grad = True)
print(f"y is {y}")
print(f"The dimension of y is {y.ndim}")
print(f"The shape of y is {y.shape}")
print(f"The data type of y is {y.dtype}")
print(f"The requires_grad of y is {y.requires_grad}")
print(f"The device of y is {y.device}")

x is [4.1]
The dimension of x is 1
The shape of x is (1,)
The data type of x is float64
y is tensor([4.1000], dtype=torch.float64, requires_grad=True)
The dimension of y is 1
The shape of y is torch.Size([1])
The data type of y is torch.float64
The requires_grad of y is True
The device of y is cpu


**Create 2-dim tensors**

In [ ]:
x = np.array([[4.1]]) # Also try x = np.array([[1, 2.3, -.5]]), np.array([[1], [2.3], [-.5]], [[1, 2], [3, 4], [5, 6]])
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")

y = torch.tensor(x, device = 'cuda')
print(f"y is {y}")
print(f"The dimension of y is {y.ndim}")
print(f"The shape of y is {y.shape}")
print(f"The data type of y is {y.dtype}")
print(f"The requires_grad of y is {y.requires_grad}")
print(f"The device of y is {y.device}")

x is [[4.1]]
The dimension of x is 2
The shape of x is (1, 1)
The data type of x is float64
y is tensor([[4.1000]], device='cuda:0', dtype=torch.float64)
The dimension of y is 2
The shape of y is torch.Size([1, 1])
The data type of y is torch.float64
The requires_grad of y is False
The device of y is cuda:0


**Create 3-dim tensors**

In [ ]:
x = np.array([[[4.1]]])
# Also try x = np.array([[[1, 2.3, -.5]]]), np.array([[[1], [2.3], [-.5]]], [[[1]], [[2.3]], [[-.5]]]), np.array([[[1, 2], [3, 4], [5, 6]], [[10, 20], [30, 40], [50, 60]]])
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")

y = torch.tensor(x, requires_grad = True, device = 'cuda')
print(f"y is {y}")
print(f"The dimension of y is {y.ndim}")
print(f"The shape of y is {y.shape}")
print(f"The data type of y is {y.dtype}")
print(f"The requires_grad of y is {y.requires_grad}")
print(f"The device of y is {y.device}")

x is [[[4.1]]]
The dimension of x is 3
The shape of x is (1, 1, 1)
The data type of x is float64
y is tensor([[[4.1000]]], device='cuda:0', dtype=torch.float64, requires_grad=True)
The dimension of y is 3
The shape of y is torch.Size([1, 1, 1])
The data type of y is torch.float64
The requires_grad of y is True
The device of y is cuda:0


# **Create special valued tensors**

* 0-dim: ```size = ()```
* 1-dim: ```size = (dim_0,)```
* 2-dim: ```size = (dim_0, dim_1)```
* 3-dim: ```size = (dim_0, dim_1, dim_2)```

**Create all 0s tensors**

In [ ]:
x = torch.zeros(size = ()) # Also try size = (1,), (3,), (1,1), (1,3), (2,3), (1,1,1), (1,1,3), (1,3,1), (3,1,1), (3,2,4)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is 0.0
The dimension of x is 0
The shape of x is torch.Size([])
The data type of x is torch.float32
The requires_grad of x is False
The device of x is cpu


**Create all 1s tensors**

In [ ]:
x = torch.ones(size = ()) # Also try size = (1,), (3,), (1,1), (1,3), (2,3), (1,1,1), (1,1,3), (1,3,1), (3,1,1), (3,2,4)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is 1.0
The dimension of x is 0
The shape of x is torch.Size([])
The data type of x is torch.float32
The requires_grad of x is False
The device of x is cpu


**Create empty tensors**

In [ ]:
x = torch.empty(size = ()) # Also try size = (1,), (3,), (1,1), (1,3), (2,3), (1,1,1), (1,1,3), (1,3,1), (3,1,1), (3,2,4)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is 1.593752907425028e-11
The dimension of x is 0
The shape of x is torch.Size([])
The data type of x is torch.float32
The requires_grad of x is False
The device of x is cpu


**Create identity matrices**

In [ ]:
x = torch.eye(4, 7)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.]])
The dimension of x is 2
The shape of x is torch.Size([4, 7])
The data type of x is torch.float32
The requires_grad of x is False
The device of x is cpu


**Create a tensor filled by a given value**

In [ ]:
x = torch.fill(torch.ones(size = (3,2)), value = 10)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is tensor([[10., 10.],
        [10., 10.],
        [10., 10.]])
The dimension of x is 2
The shape of x is torch.Size([3, 2])
The data type of x is torch.float32
The requires_grad of x is False
The device of x is cpu


# **Create random-valued tensors**

* ```torch.rand```: Generate random variables **uniformly distributed between 0 and 1**
* ```torch.randint```: Generate **integer** random variables uniformly distributed between customized lower and upper bounds
* ```torch.randn```: Generate **standard normal (mean 0, variance 1)** random variables
* ```torch.normal```: Generate **normal** random variables with **customized mean and variance**

In [ ]:
x = torch.rand(size = ()) # Also try size = (1,), (3,), (1,1), (1,3), (2,3), (1,1,1), (1,1,3), (1,3,1), (3,1,1), (3,2,4)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is 0.2660679221153259
The dimension of x is 0
The shape of x is torch.Size([])
The data type of x is torch.float32
The requires_grad of x is False
The device of x is cpu


In [ ]:
x = torch.randint(low = -4, high = 8, size = ()) # Also try size = (1,), (3,), (1,1), (1,3), (2,3), (1,1,1), (1,1,3), (1,3,1), (3,1,1), (3,2,4)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is -2
The dimension of x is 0
The shape of x is torch.Size([])
The data type of x is torch.int64
The requires_grad of x is False
The device of x is cpu


In [ ]:
x = torch.randn(size = ()) # Also try size = (1,), (3,), (1,1), (1,3), (2,3), (1,1,1), (1,1,3), (1,3,1), (3,1,1), (3,2,4)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is 0.3186081647872925
The dimension of x is 0
The shape of x is torch.Size([])
The data type of x is torch.float32
The requires_grad of x is False
The device of x is cpu


In [ ]:
x = torch.normal(mean = 1, std = .5, size = ()) # Also try size = (1,), (3,), (1,1), (1,3), (2,3), (1,1,1), (1,1,3), (1,3,1), (3,1,1), (3,2,4)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is 1.2724189758300781
The dimension of x is 0
The shape of x is torch.Size([])
The data type of x is torch.float32
The requires_grad of x is False
The device of x is cpu


# **Create new tensors from other tensors**

* Use ```XYZ_like()``` method

* Two tensors have the same data type.

* Two tensors have the same device.

* The new tensor's `requires_grad` is `False` by default.

In [ ]:
y = torch.tensor([[3, 5], [-2.2, 1], [2.8, -3]], requires_grad = True, device = "cuda")

x = torch.zeros_like(y)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], device='cuda:0')
The dimension of x is 2
The shape of x is torch.Size([3, 2])
The data type of x is torch.float32
The requires_grad of x is False
The device of x is cuda:0


In [ ]:
y = torch.randn(size = (3,4), requires_grad = True, device = "cuda") > -.5

x = torch.ones_like(y)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]], device='cuda:0')
The dimension of x is 2
The shape of x is torch.Size([3, 4])
The data type of x is torch.bool
The requires_grad of x is False
The device of x is cuda:0


In [ ]:
y = torch.tensor([[3, 5], [-2, 1], [2, -3.2]]) # If y.dtype is integer, and you generate x with randn_like, you will see an error

x = torch.randn_like(y)
print(f"x is {x}")
print(f"The dimension of x is {x.ndim}")
print(f"The shape of x is {x.shape}")
print(f"The data type of x is {x.dtype}")
print(f"The requires_grad of x is {x.requires_grad}")
print(f"The device of x is {x.device}")

x is tensor([[ 0.6989,  1.8168],
        [ 1.3236, -0.3463],
        [-1.3270, -0.5947]])
The dimension of x is 2
The shape of x is torch.Size([3, 2])
The data type of x is torch.float32
The requires_grad of x is False
The device of x is cpu


# **Reset tensor values**

**Fill all entries with the same value in place: ```fill_()```**

* In PyTorch, typically, a method ending with ```_``` means the change is in place.

* If you want the change to be in place, then `requires_grad` should be `False`.



In [ ]:
x = torch.randn(3, 4)
print(x)

x.fill_(10)
print(x)
print(x.dtype)

tensor([[ 1.1080,  0.8949, -0.2635, -0.4322],
        [-0.5563, -1.8438, -0.0640, -2.2998],
        [-1.0601,  0.6417,  0.5191, -0.4885]])
tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])
torch.float32


In [ ]:
x = torch.randn(size = (3,4), requires_grad = True)
print(x)

x.fill_(10) # This is wrong, since requires_grad is True
print(x)
print(x.dtype)

tensor([[-0.4098,  0.2456, -0.4727, -0.8858],
        [-0.4208, -1.9604, -0.9814, -1.3918],
        [-0.2472,  1.7221,  0.8572, -0.3032]], requires_grad=True)


RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

**Fill all entries with 0 in place: ```zero_()```**




In [ ]:
x = torch.randn(3, 4)
print(x)

x.zero_()
print(x)
print(x.dtype)

tensor([[ 0.6039,  0.4810, -0.1428,  0.5128],
        [ 0.7284,  0.4404,  0.4797,  0.2868],
        [-0.1306, -1.4231,  0.5470, -0.4514]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32


In [ ]:
x = torch.randn(size = (3,4), requires_grad = True)
print(x)

x.zero_() # This is wrong, since requires_grad is True
print(x)
print(x.dtype)

tensor([[ 0.4976, -0.6473,  0.4057,  1.5281],
        [ 1.0327, -0.6255, -0.1731, -0.3053],
        [ 1.2336, -1.3021, -0.0447,  0.7978]], requires_grad=True)


RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

# **Convert tensors to NumPy arrays**



**Method 1:**

Let `x` be a tensor with any values of its attributes `requires_grad` and `device`.

You can "brutally" convert it to a NumPy array by calling

```
x.numpy(force = True)
```

Note: The default value for `force` is `False`.

In [ ]:
x = torch.randn(size = (3,4), requires_grad = True, device = "cuda")
print(x)
print(type(x))
print(x.requires_grad)
print(x.device)

y = x.numpy(force = True)
print(y)
print(type(y))

z = x.numpy(force = False) # This is wrong, since x.requires_grad is True and x.device is "cuda"
print(z)
print(type(z))

tensor([[ 1.0713, -0.8501,  0.0907,  0.1724],
        [ 0.3786,  1.0956, -1.1172, -1.5837],
        [ 1.0746, -1.0395,  1.9190,  1.1452]], device='cuda:0',
       requires_grad=True)
<class 'torch.Tensor'>
True
cuda:0
[[ 1.0713357  -0.85010535  0.09069522  0.17239945]
 [ 0.37855485  1.0956013  -1.1171509  -1.5836651 ]
 [ 1.0745716  -1.0394528   1.9189519   1.1451633 ]]
<class 'numpy.ndarray'>


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
x = torch.randn(size = (3,4), requires_grad = True, device = "cpu")
print(x)
print(type(x))
print(x.requires_grad)
print(x.device)

y = x.numpy(force = True)
print(y)
print(type(y))

z = x.numpy(force = False) # This is wrong, since x.requires_grad is True
print(z)
print(type(z))

In [ ]:
x = torch.randn(size = (3,4), requires_grad = False, device = "cuda")
print(x)
print(type(x))
print(x.requires_grad)
print(x.device)

y = x.numpy(force = True)
print(y)
print(type(y))

z = x.numpy(force = False) # This is wrong, since x.device is "cuda"
print(z)
print(type(z))

In [ ]:
x = torch.randn(size = (3,4), requires_grad = False, device = "cpu")
print(x)
print(type(x))
print(x.requires_grad)
print(x.device)

y = x.numpy(force = True)
print(y)
print(type(y))

z = x.numpy(force = False) # This is OK, since x.requires_grad is False and x.device is "cpu"
print(z)
print(type(z))

tensor([[ 0.0382, -0.0680, -1.6463, -0.4295],
        [ 1.5272,  0.6076, -0.5480,  0.3087],
        [ 2.9826, -0.9989,  0.3280,  1.4760]])
<class 'torch.Tensor'>
False
cpu
[[ 0.03818969 -0.06801278 -1.64634    -0.4294931 ]
 [ 1.5271767   0.60764503 -0.5479615   0.30870667]
 [ 2.982647   -0.99886817  0.3279943   1.4759771 ]]
<class 'numpy.ndarray'>
[[ 0.03818969 -0.06801278 -1.64634    -0.4294931 ]
 [ 1.5271767   0.60764503 -0.5479615   0.30870667]
 [ 2.982647   -0.99886817  0.3279943   1.4759771 ]]
<class 'numpy.ndarray'>


**Method 2**

Let `x` be a PyTorch tensor.

1. If `x.requires_grad` is `True`, then use `x.detach()` to create another tensor whose `requires_grad` is `False`.

2. If `x.device` is `cuda`, then use `x.to(device = "cpu")` to create another tensor who is on `cpu`.

Then you can call `.numpy()` (or equivalently `.numpy(force = False`).

In [ ]:
x = torch.randn(size = (3,4), requires_grad = True, device = "cuda")
print(x)
print(type(x))
print(x.requires_grad)
print(x.device)

x1 = x.detach()
print(x1)
print(type(x1))
print(x1.requires_grad)
print(x1.device)

x2 = x1.to(device = "cpu")
print(x2)
print(type(x2))
print(x2.requires_grad)
print(x2.device)

y = x2.numpy()
print(y)
print(type(y))

tensor([[ 0.0763,  0.9147, -1.0417, -0.2569],
        [-1.9785,  1.4578, -1.3262, -1.4279],
        [ 1.2230, -0.0184,  0.0622, -0.0082]], device='cuda:0',
       requires_grad=True)
<class 'torch.Tensor'>
True
cuda:0
tensor([[ 0.0763,  0.9147, -1.0417, -0.2569],
        [-1.9785,  1.4578, -1.3262, -1.4279],
        [ 1.2230, -0.0184,  0.0622, -0.0082]], device='cuda:0')
<class 'torch.Tensor'>
False
cuda:0
tensor([[ 0.0763,  0.9147, -1.0417, -0.2569],
        [-1.9785,  1.4578, -1.3262, -1.4279],
        [ 1.2230, -0.0184,  0.0622, -0.0082]])
<class 'torch.Tensor'>
False
cpu
[[ 0.07626496  0.91472805 -1.0416878  -0.2568592 ]
 [-1.978469    1.4578252  -1.3261569  -1.4279339 ]
 [ 1.2229884  -0.01839632  0.06221934 -0.00818261]]
<class 'numpy.ndarray'>


# **Convert a tensor with only ONE element to a pure number**

* Syntax: `.item()`.

* The tensor can be with any dimension, such as `()`, `(1,)`, `(1,1)`, `(1,1,1)`.

* `requires_grad` can be either `True` or `False`.

* `device` can be either `cpu` or `cuda`.

In [ ]:
x = torch.tensor([[3.5]], requires_grad = True, device = "cuda")
print(x)
print(type(x))

y = x.item()
print(y)
print(type(y))

tensor([[3.5000]], device='cuda:0', requires_grad=True)
<class 'torch.Tensor'>
3.5
<class 'float'>


**Copyright  Beaver-Edge AI Institute. All Rights Reserved. No part of this document may be copied or reproduced without the written permission of Beaver-Edge AI Institute.**