<a href="https://colab.research.google.com/github/YuanChenhang/USAAIO/blob/main/PyTorch_indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import necessary libraries**

In [ ]:
import torch

# **Indexing**

In [ ]:
x = torch.rand(7).reshape(7,)
print(x)

# Indexing
y = x[1]
print(y)

tensor([0.8111, 0.0937, 0.8011, 0.9179, 0.5744, 0.2034, 0.5197])
tensor(0.0937)


In [ ]:
x = torch.rand((5,6))
print(x)
print("")
# Indexing
y = x[1,4]
print(y)

tensor([[0.1357, 0.7486, 0.6933, 0.0917, 0.2465, 0.2193],
        [0.4331, 0.8517, 0.8924, 0.3521, 0.3922, 0.1072],
        [0.4028, 0.7708, 0.3826, 0.2728, 0.0787, 0.5641],
        [0.3833, 0.5672, 0.3658, 0.9601, 0.8109, 0.6786],
        [0.2779, 0.2358, 0.8922, 0.4519, 0.2099, 0.5447]])

tensor(0.3922)


In [ ]:
x = torch.rand((5,3,4))
print(x)
print("")
y = x[1,1,3]
print(y)

tensor([[[0.6416, 0.9945, 0.5453, 0.4142],
         [0.4823, 0.7312, 0.6732, 0.4461],
         [0.2108, 0.3561, 0.4482, 0.5135]],

        [[0.7204, 0.4925, 0.3334, 0.6385],
         [0.9922, 0.5272, 0.7578, 0.6822],
         [0.2105, 0.3769, 0.0815, 0.9806]],

        [[0.4448, 0.4854, 0.6517, 0.9726],
         [0.5143, 0.3596, 0.0104, 0.5175],
         [0.1423, 0.9046, 0.5035, 0.5024]],

        [[0.6218, 0.1064, 0.4329, 0.8624],
         [0.3705, 0.6891, 0.2780, 0.6223],
         [0.5529, 0.0290, 0.2884, 0.8481]],

        [[0.8416, 0.7694, 0.6001, 0.2365],
         [0.5645, 0.8518, 0.3860, 0.3041],
         [0.7443, 0.6535, 0.3371, 0.6902]]])

tensor(0.6822)


**Indexing is a view, not a copy**

In [ ]:
y += 1
print(y)

print(x)

tensor(1.6822)
tensor([[[0.6416, 0.9945, 0.5453, 0.4142],
         [0.4823, 0.7312, 0.6732, 0.4461],
         [0.2108, 0.3561, 0.4482, 0.5135]],

        [[0.7204, 0.4925, 0.3334, 0.6385],
         [0.9922, 0.5272, 0.7578, 1.6822],
         [0.2105, 0.3769, 0.0815, 0.9806]],

        [[0.4448, 0.4854, 0.6517, 0.9726],
         [0.5143, 0.3596, 0.0104, 0.5175],
         [0.1423, 0.9046, 0.5035, 0.5024]],

        [[0.6218, 0.1064, 0.4329, 0.8624],
         [0.3705, 0.6891, 0.2780, 0.6223],
         [0.5529, 0.0290, 0.2884, 0.8481]],

        [[0.8416, 0.7694, 0.6001, 0.2365],
         [0.5645, 0.8518, 0.3860, 0.3041],
         [0.7443, 0.6535, 0.3371, 0.6902]]])


# **Slicing**

In [ ]:
x = torch.rand(12).reshape(12,)
print(x)
print()
# Indexing
y = x[1:10]
print(y)

tensor([0.9320, 0.8724, 0.5516, 0.0387, 0.4658, 0.4967, 0.3773, 0.4989, 0.2822,
        0.1292, 0.2299, 0.0231])

tensor([0.8724, 0.5516, 0.0387, 0.4658, 0.4967, 0.3773, 0.4989, 0.2822, 0.1292])


In [ ]:
x = torch.arange(240).reshape(2,3,4,10)
print(x)

# Slicing
y = x[0, :, 3, 2:-1:2]
print(y)

tensor([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
          [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39]],

         [[ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
          [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79]],

         [[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
          [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]],


        [[[120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
          [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
          [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
          [150, 151, 152, 153, 154, 155, 156, 157, 158, 159]],

**Slicing is a view, not a copy**

In [ ]:
y *= -100
print(y)

print(x)

tensor([[ -3200,  -3400,  -3600,  -3800],
        [ -7200,  -7400,  -7600,  -7800],
        [-11200, -11400, -11600, -11800]])
tensor([[[[     0,      1,      2,      3,      4,      5,      6,      7,
                8,      9],
          [    10,     11,     12,     13,     14,     15,     16,     17,
               18,     19],
          [    20,     21,     22,     23,     24,     25,     26,     27,
               28,     29],
          [    30,     31,  -3200,     33,  -3400,     35,  -3600,     37,
            -3800,     39]],

         [[    40,     41,     42,     43,     44,     45,     46,     47,
               48,     49],
          [    50,     51,     52,     53,     54,     55,     56,     57,
               58,     59],
          [    60,     61,     62,     63,     64,     65,     66,     67,
               68,     69],
          [    70,     71,  -7200,     73,  -7400,     75,  -7600,     77,
            -7800,     79]],

         [[    80,     81,     82,     83,   

# **Fancy indexing: Boolean**

In [ ]:
x = torch.arange(24).reshape(2,3,4)
print(x)

criteron = (x > 10) & (x % 2 == 1)
print(criteron)

# Boolean fancy indexing
y = x[criteron]
print(y)
print(y.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[False, False, False, False],
         [False, False, False, False],
         [False, False, False,  True]],

        [[False,  True, False,  True],
         [False,  True, False,  True],
         [False,  True, False,  True]]])
tensor([11, 13, 15, 17, 19, 21, 23])
torch.Size([7])


**Boolean fancy indexing is a copy, not a view**

In [ ]:
y *= -100
print(y)

print(x)

tensor([-1100, -1300, -1500, -1700, -1900, -2100, -2300])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


# **Fancy indexing: Coordinates**

Example: `x` has dimension 4. We choose the following coordinates `x[i,j,k,l]`:

* Indexing on `(i,k) = (0,3), (1,3), (0,1), (0,1), (1,2), (0,2)`

* Slicing on `j: [:]`

* Slicing on `l: [1:-1:2]`

In [ ]:
x = torch.arange(120).reshape(2,3,4,5)
print(x)

# Coordinates fancy indexing
y = x[[0, 1, 0, 0, 1, 0], :, [3, 3, 1, 1, 2, 2], 1:-1:2]
print(y)
print(y.shape)

tensor([[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]],

         [[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]]],


        [[[ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74],
          [ 75,  76,  77,  78,  79]],

         [[ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119]]]])
tensor([[[ 16,  18],
         [ 36,  38],
         [ 56,  58]],

        [[ 76,  78],
         [ 

**Coordinates fancy indexing is a copy, not a view**

In [ ]:
y *= -100
print(y)

print(x)

tensor([[[ -1600,  -1800],
         [ -3600,  -3800],
         [ -5600,  -5800]],

        [[ -7600,  -7800],
         [ -9600,  -9800],
         [-11600, -11800]],

        [[  -600,   -800],
         [ -2600,  -2800],
         [ -4600,  -4800]],

        [[  -600,   -800],
         [ -2600,  -2800],
         [ -4600,  -4800]],

        [[ -7100,  -7300],
         [ -9100,  -9300],
         [-11100, -11300]],

        [[ -1100,  -1300],
         [ -3100,  -3300],
         [ -5100,  -5300]]])
tensor([[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]],

         [[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]]],


        [[[ 60,  61,  62,  63,  64],
          [ 6

**Exercise**

Define

```
x = torch.arange(24).reshape(2,3,4)
```

Do the following coordinates fancy indexing. For each one, print out its value and its shape.

* (1-dim output) `x[[0,1,1,0], [2,0,1,1], [1,0,3,2]]`

* (multi-dim output) `x[[[0,1,0],[1,1,0]], [[2,1,2],[0,1,2]], [[2,3,0],[1,0,2]]]`

* (broadcasting) `x[torch.tensor([1,0,1]).unsqueeze(-1), torch.tensor([0,1,2,1,2]), [[2,3,0,1,2],[1,0,2,0,0],[1,3,3,2,0]]]`

* (fancy indexing + slicing) `x[[[0,1,0],[1,1,0]], [[2,1,2],[0,1,2]], :]`

* (fancy indexing + slicing) `x[[[0,1,0],[1,1,0]], [[2,1,2],[0,1,2]], ::2]`

* (fancy indexing + slicing) `x[[[0,1,0],[1,1,0]], :, 1:-1:]`

* (fancy indexing + broadcasting + slicing)
`x[:, torch.tensor([2,0,2]).unsqueeze(-1) , [[2,3,0,1,2],[1,0,2,0,0],[1,3,3,2,0]]]`

In [ ]:
x = torch.arange(24).reshape(2,3,4)
print(x)

print(x[[0,1,1,0], [2,0,1,1], [1,0,3,2]])

print(x[[[0,1,0],[1,1,0]], [[2,1,2],[0,1,2]], [[2,3,0],[1,0,2]]])

print(x[torch.tensor([1,0,1]).unsqueeze(-1), torch.tensor([0,1,2,1,2]), [[2,3,0,1,2],[1,0,2,0,0],[1,3,3,2,0]]])

print(x[[[0,1,0],[1,1,0]], [[2,1,2],[0,1,2]], :])

print(x[[[0,1,0],[1,1,0]], [[2,1,2],[0,1,2]], ::2])

print(x[[[0,1,0],[1,1,0]], :, 1:-1:])

print(x[:, torch.tensor([2,0,2]).unsqueeze(-1) , [[2,3,0,1,2],[1,0,2,0,0],[1,3,3,2,0]]])

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([ 9, 12, 19,  6])
tensor([[10, 19,  8],
        [13, 16, 10]])
tensor([[14, 19, 20, 17, 22],
        [ 1,  4, 10,  4,  8],
        [13, 19, 23, 18, 20]])
tensor([[[ 8,  9, 10, 11],
         [16, 17, 18, 19],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [ 8,  9, 10, 11]]])
tensor([[[ 8, 10],
         [16, 18],
         [ 8, 10]],

        [[12, 14],
         [16, 18],
         [ 8, 10]]])
tensor([[[[ 1,  2],
          [ 5,  6],
          [ 9, 10]],

         [[13, 14],
          [17, 18],
          [21, 22]],

         [[ 1,  2],
          [ 5,  6],
          [ 9, 10]]],


        [[[13, 14],
          [17, 18],
          [21, 22]],

         [[13, 14],
          [17, 18],
          [21, 22]],

         [[ 1,  2],
          [ 5,  6],
          [ 9, 10]]]])
tensor([[[10, 

# **Exercise**

Consider training a BERT model in large language models (LLM).

* Let `output_tokens` be with the shape `(num_samples,length)` and value taken from `0, 1, ..., vocab_size -1`. So `output_tokens[n,l]` is the ground-truth output from position `l` in sample `n`.

* Let `logits` be with the shape `(num_samples,length,vocab_size)`. So `logits[n,l,k]` is the predict logit of token `k` on position `l` in sample `n`.

* Let `attention_mask` be a boolean tensor with shape `(num_samples,length)`. So `attention_mask[n,l]` is `True` if position `l` in sample `n` needs to be attended (that is, we need to learn from this position). Otherwise, if `attention_mask[n,l]` is `False`, then we skip learning from position `l` in sample `n`.

Write code to compute the cross entropy loss.



In [ ]:
# Hyperparameters
num_samples = 8
length = 10
vocab_size = 4

# Instantiate ground-truth output
output_tokens = torch.randint(0, vocab_size, (num_samples, length))
print(output_tokens.shape)

# Instantiate predicted logits
logits = torch.randn(num_samples, length, vocab_size)
print(logits.shape)

# Instantiate attention_mask
attention_mask = torch.randn(num_samples, length) > 0.3
print(attention_mask.shape)

# Compute predicted log probability for each token on each position in each sample
log_prob = logits - torch.log(torch.sum(torch.exp(logits), dim=2, keepdim=True))
print(log_prob.shape)

# Compute log_prob for the ground-truth output token on each position in each sample
log_prob_true = log_prob[torch.arange(num_samples).unsqueeze(-1), torch.arange(length), output_tokens]
print(log_prob_true.shape)

# Compute the cross entropy loss on samples and positions with attention
loss = torch.mean(- log_prob_true[attention_mask])
print(loss)

torch.Size([8, 10])
torch.Size([8, 10, 4])
torch.Size([8, 10])
torch.Size([8, 10, 4])
torch.Size([8, 10])
tensor(1.5417)


**Copyright  Beaver-Edge AI Institute. All Rights Reserved. No part of this document may be copied or reproduced without the written permission of Beaver-Edge AI Institute.**